# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaFuncional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Areas funcionales',
            },
        ),
        migrations.CreateModel(
            name='CategoriaCobertura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Categorias de cobertura',
            },
        ),
        migrations.CreateModel(
            name='CategoriaInterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Categorias internas',
            },
        ),
        migrations.CreateModel(
            name='CategoriaOrigen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Categorias de origen',
            },
        ),
        migrations.CreateModel(
            name='CategoriaTamanio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Catagoria de tama\xf1os',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=300)),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo Electr\xf3nico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Tel\xe9fono')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('comentarios', models.CharField(blank=True, max_length=2000)),
                ('fecha_nac', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=500, verbose_name='Dirreci\xf3n Oficina')),
                ('publicidad', models.CharField(blank=True, max_length=2)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_area', to='crm.AreaFuncional')),
            ],
            options={
                'ordering': ('id', 'nombre'),
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='EjecutivoComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=300)),
                ('mail', models.EmailField(max_length=254, verbose_name='Correo Electr\xf3nico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Tel\xe9fono')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('comentarios', models.CharField(blank=True, max_length=2000)),
                ('fecha_ing', models.DateTimeField(verbose_name='Fecha de Ingreso')),
                ('fecha_sal', models.DateTimeField(verbose_name='Fecha de salida')),
                ('date_insert', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre'),
                'verbose_name_plural': 'Ejecutivos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('razon_social', models.CharField(blank=True, max_length=300)),
                ('direccion', models.CharField(blank=True, max_length=500)),
                ('comentarios', models.CharField(blank=True, max_length=2000)),
                ('date_insert', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'razon_social'),
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='EstatusActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Estatus de las actividades',
            },
        ),
        migrations.CreateModel(
            name='EstatusRelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Estatus de la ralaci\xf3n',
            },
        ),
        migrations.CreateModel(
            name='FuenteInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Fuentes iniciales',
            },
        ),
        migrations.CreateModel(
            name='Industria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Industrias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Productos de ventas',
            },
        ),
        migrations.CreateModel(
            name='PuestoInterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Puestos internos',
            },
        ),
        migrations.CreateModel(
            name='RolEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='TipoIndustria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Tipos de industrias',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_actividad', to='crm.Industria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cobertura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_cobertura', to='crm.CategoriaCobertura'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='industria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_industria', to='crm.Industria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='interno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_interno', to='crm.Industria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_origen', to='crm.Industria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='relacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_relacion', to='crm.Industria'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tamanio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_tamanio', to='crm.CategoriaTamanio'),
        ),
        migrations.AddField(
            model_name='ejecutivocomercial',
            name='puesto_interno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivo_puesto_interno', to='crm.PuestoInterno'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_empresa', to='crm.Empresa'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='puesto_interno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_puesto_interno', to='crm.PuestoInterno'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_rol', to='crm.RolEmpresa'),
        ),
    ]
