# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_actividad', to='crm.EstatusActividad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='interno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_interno', to='crm.CategoriaInterna'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='origen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_origen', to='crm.CategoriaOrigen'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='relacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_relacion', to='crm.EstatusRelacion'),
        ),
    ]
