# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170517_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lnc', models.DateTimeField(verbose_name='Fecha de lead no calif')),
                ('fecha_lc', models.DateTimeField(verbose_name='Fecha de lead calif')),
                ('fecha_op', models.DateTimeField(verbose_name='Fecha de operaci\xf3n')),
                ('fecha_neg', models.DateTimeField(verbose_name='Fecha de negociaci\xf3n')),
                ('fecha_cie', models.DateTimeField(verbose_name='Fecha de cierre')),
            ],
            options={
                'ordering': ('id', 'fecha_lnc'),
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='LeadDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimado', models.FloatField(null=True)),
                ('comentarios', models.CharField(blank=True, max_length=2000)),
                ('causa_salida', models.CharField(blank=True, max_length=2000)),
                ('tipo', models.IntegerField(choices=[(5, 'CIE'), (3, 'OP'), (2, 'LC'), (4, 'NEG'), (1, 'LNC')], default=1)),
            ],
            options={
                'ordering': ('id', 'empresa'),
                'verbose_name_plural': 'Deatelles Leads',
            },
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre', 'modified'),
                'verbose_name_plural': 'Plazas',
            },
        ),
        migrations.AlterField(
            model_name='contacto',
            name='publicidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_lead', to='crm.Contacto'),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='ejecutivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivo_lead', to='crm.EjecutivoComercial'),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_lead', to='crm.Empresa'),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='crm.Lead'),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='plaza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_plaza', to='crm.Plaza'),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_lead', to='crm.Producto'),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='relacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_relacion', to='crm.EstatusRelacion'),
        ),
    ]
