# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170523_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaddetalle',
            name='producto',
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='producto',
            field=models.ManyToManyField(null=True, related_name='producto_lead', to='crm.Producto'),
        ),
    ]
