# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20170523_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='fecha_cie',
            field=models.DateTimeField(null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fecha_lc',
            field=models.DateTimeField(null=True, verbose_name='Fecha de lead calif'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fecha_lnc',
            field=models.DateTimeField(null=True, verbose_name='Fecha de lead no calif'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fecha_neg',
            field=models.DateTimeField(null=True, verbose_name='Fecha de negociaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='fecha_op',
            field=models.DateTimeField(null=True, verbose_name='Fecha de operaci\xf3n'),
        ),
    ]
