# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20170523_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddetalle',
            name='producto',
            field=models.ManyToManyField(related_name='producto_lead', to='crm.Producto'),
        ),
    ]
