# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_leaddetalle_es_vigente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapasLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('id', 'nombre'),
                'verbose_name_plural': 'Etapas lead',
            },
        ),
        migrations.RemoveField(
            model_name='leaddetalle',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='ejecutivocomercial',
            name='fecha_sal',
            field=models.DateTimeField(blank=True, verbose_name='Fecha de salida'),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='etapa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_etapa', to='crm.EtapasLeads'),
        ),
    ]
