# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20170523_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaddetalle',
            name='ejecutivo',
        ),
        migrations.AddField(
            model_name='lead',
            name='fecha_baja',
            field=models.DateTimeField(null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='ejecutivo_primario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivo_prim_lead', to='crm.EjecutivoComercial'),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='ejecutivo_principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivo_prin_lead', to='crm.EjecutivoComercial'),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='ejecutivo_secundario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivo_sec_lead', to='crm.EjecutivoComercial'),
        ),
    ]
