# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20170524_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaddetalle',
            name='relacion',
        ),
        migrations.AddField(
            model_name='lead',
            name='nombre',
            field=models.CharField(default='Oportunidad', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='fuente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_fuente', to='crm.FuenteInicial'),
        ),
    ]
