# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20170524_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddetalle',
            name='fecha_plan_init',
            field=models.DateTimeField(null=True, verbose_name='Fecha planeada de inicio'),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='fecha_real_init',
            field=models.DateTimeField(null=True, verbose_name='Fecha real de inicio'),
        ),
    ]
