# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20170526_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areafuncional',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Areas funcionales'},
        ),
        migrations.AlterModelOptions(
            name='categoriacobertura',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Categorias de cobertura'},
        ),
        migrations.AlterModelOptions(
            name='categoriainterna',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Categorias internas'},
        ),
        migrations.AlterModelOptions(
            name='categoriaorigen',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Categorias de origen'},
        ),
        migrations.AlterModelOptions(
            name='categoriatamanio',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Catagoria de tama\xf1os'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='estatusactividad',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Estatus de las actividades'},
        ),
        migrations.AlterModelOptions(
            name='estatusrelacion',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Estatus de la ralaci\xf3n'},
        ),
        migrations.AlterModelOptions(
            name='fuenteinicial',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Fuentes iniciales'},
        ),
        migrations.AlterModelOptions(
            name='industria',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Industrias'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='plaza',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Plazas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Productos de ventas'},
        ),
        migrations.AlterModelOptions(
            name='puestointerno',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Puestos internos'},
        ),
        migrations.AlterModelOptions(
            name='rolempresa',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='tipoindustria',
            options={'ordering': ('id', 'nombre'), 'verbose_name_plural': 'Tipos de industrias'},
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='created',
            new_name='date_insert',
        ),
        migrations.AddField(
            model_name='contacto',
            name='date_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='date_insert',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leaddetalle',
            name='date_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
