# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20170526_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='ejecutivocomercial',
            name='puesto',
        ),
        migrations.AlterField(
            model_name='ejecutivocomercial',
            name='fecha_ing',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='ejecutivocomercial',
            name='fecha_sal',
            field=models.DateTimeField(null=True, verbose_name='Fecha de salida'),
        ),
    ]
