# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20170529_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddetalle',
            name='fecha_plan_init',
            field=models.DateTimeField(default=None, null=True, verbose_name='Fecha planeada de inicio'),
        ),
        migrations.AlterField(
            model_name='leaddetalle',
            name='fecha_real_init',
            field=models.DateTimeField(default=None, null=True, verbose_name='Fecha real de inicio'),
        ),
    ]
