# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20170529_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaddetalle',
            name='fecha_plan_init',
        ),
        migrations.RemoveField(
            model_name='leaddetalle',
            name='fecha_real_init',
        ),
        migrations.AddField(
            model_name='lead',
            name='fecha_plan_init',
            field=models.DateTimeField(null=True, verbose_name='Fecha planeada de inicio'),
        ),
        migrations.AddField(
            model_name='lead',
            name='fecha_real_init',
            field=models.DateTimeField(null=True, verbose_name='Fecha real de inicio'),
        ),
    ]
