# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20170529_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejecutivocomercial',
            name='puesto_interno',
        ),
        migrations.AddField(
            model_name='ejecutivocomercial',
            name='puesto',
            field=models.CharField(default='Trebajador', max_length=100),
            preserve_default=False,
        ),
    ]
