# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20170529_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddetalle',
            name='ejecutivo_primario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivo_prim_lead', to='crm.EjecutivoComercial'),
        ),
        migrations.AlterField(
            model_name='leaddetalle',
            name='ejecutivo_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivo_prin_lead', to='crm.EjecutivoComercial'),
        ),
        migrations.AlterField(
            model_name='leaddetalle',
            name='ejecutivo_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivo_sec_lead', to='crm.EjecutivoComercial'),
        ),
    ]
